### ISSUE TITLE
Running Imagenet100 Exp

### ISSUE THREAD

**Issue by AmeenAli** [wvangansbeke/Unsupervised-Classification#10]
Hello,
i want to run an experiment on imagenet100 using the config file : "moco_imagenet100.yml"
however running as : "python simclr.py --config_env configs/env.yml --config_exp configs/pretext/moco_imagenet100.yml"
give the following assertion : 
    if p['augmentation_strategy'] == 'standard':
KeyError: 'augmentation_strategy'

**Comment by wvangansbeke** [comment]
Hi @AmeenAli,

We used the pretrained model of MoCo instead of SimCLR for ImageNet. So you have to run `moco.py` instead of `simclr.py` here. The file `moco.py` downloads their pretrained model automatically. It would take a long time to train this yourself actually. I believe this model was trained for 800 epochs.

**Comment by AmeenAli** [comment]
> Hi @AmeenAli,
> 
> We used the pretrained model of MoCo instead of SimCLR for ImageNet. So you have to run `moco.py` instead of `simclr.py` here. The file `moco.py` downloads their pretrained model automatically. It would take a long time to train this yourself actually. I believe this model was trained for 800 epochs.

Thanks, this uses resnet50 from resnet_cifar.py but with BottleNeck blocks?

**Comment by wvangansbeke** [comment]
Hi @AmeenAli,

No it loads the classic ResNet-50 from Torchvision. Check out [this line](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/utils/common_config.py#L60).
