### ISSUE TITLE
Some files in the model are not used, such as models.py and losses.py!

### ISSUE THREAD

**Issue by cxr12345** [wvangansbeke/Unsupervised-Classification#17]
Dear author：
I am a loyal fan of yours. Recently I discovered that your code is open source, and it has attracted many stars in a short period of time. But I have some doubts. If you have time to trouble you, I find that the models.py and losses.py files in the code have not been imported by other files and have become independent. What are their functions? Why do you want to do this?

**Comment by wvangansbeke** [comment]
Hi @cxr12345,

I'm not completely sure what your problem is. Please have a look at `utils/common_config.py`. For example `losses.py` is imported [here](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/utils/common_config.py#L16) and models is imported [here](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/utils/common_config.py#L48). A simple `grep -rn string` command in the terminal will tell you where the string is used and in which files.

If it's still unclear, let me know.

**Comment by cxr12345** [comment]
Thank you so much for your reply, I understand, thank you and your team！

**Comment by wvangansbeke** [comment]
Cheers.
