### ISSUE TITLE
Some questions about the clustering step

### ISSUE THREAD

**Issue by lstefanou** [wvangansbeke/Unsupervised-Classification#20]
Hi,

According to the paper you freeze the weights of the contrastive backbone and only update the weights of the clustering heads. However; in this implementation it seems by default both the backbone and heads are trained (see [here](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/scan.py#L56) and [here](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/utils/train_utils.py#L43))

Furthermore the entropy weight is set to 5 according to the paper, but in the implementation the default is 2 (see [here](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/losses/losses.py#L90))

I would greatly appreciate if you could let me know which options are correct! I've tried training with the backbone enabled, which leads to very fast convergence; which I guess is always suspicious, hence my asking.

**Comment by wvangansbeke** [comment]
Hi @lstefanou,

- For the smaller datasets (CIFAR10, CIFAR100-20, STL10) we train the complete network as is mentioned in the paper. We only freeze the backbone for ImageNet during the clustering step because ImageNet has a lot of classes (i.e. 1000). This means that you would need to train with a very large batch size such that the the entropy term in the loss makes sense. We also mention this in the implementation details in the paper. 

- Good catch. I will adjust the comment because the default value for this parameter is indeed 5 (as we used in the config files).

- Actually this makes a lot of sense. Due to the pretext task, the obtained feature space is already extremely informative (see the quality of the nearest neighbours in the paper). That's why we propose to decouple feature learning and clustering. 
The clustering loss simply divides the dataset into C clusters and imposes consistent predictions between a sample and its nearest neighbours (i.e. extra invariances as opposed to a sample only its own augmentations). Indeed you should already get close to prior SOTA accuracy after two epochs when training with the clustering loss. 

Hope this helps.
