### ISSUE TITLE
Attributing clusters to the correct classes

### ISSUE THREAD

**Issue by alceubissoto** [wvangansbeke/Unsupervised-Classification#29]
Hello @wvangansbeke! Congratulations on your work, and thanks for sharing a very organized code! I believe it is a very important (but often overlooked) step of research. 

I'm playing with your code in a custom dataset, and I wondered if there is any code that "aligns" the clusters to the correct classes, or if it must be done manually... For example, in CIFAR-10, you use the labeled data to evaluate the unsupervised procedure's performance. How do you know that cluster 3 (for example) corresponds to the class "truck"? Also, having more clusters than necessary (using the example of the paper, 20 for CIFAR-10), how do you decide which clusters to merge to compose the classes?

Thanks again!

**Comment by wvangansbeke** [comment]
Hi @alceubissoto,

Thanks. I appreciate you checking out the code!

Good question. Indeed, the found clusters are not guaranteed to align perfectly with the ground truth. It completely depends on what you're interested in the end. However, in order to evaluate, we perform an hungarian matching algorithm ([this function](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/utils/evaluate_utils.py#L123)) to maximize the overlap with the ground truth classes, which is also used in prior work, e.g. IIC. For overclustering, the evaluation is slightly different. Here, a 'one-to-one' mapping is not possible, therefore we simply compute the majority ground truth class for each cluster and assign all samples of that cluster to that particular class during evaluation. Ideally you would solve a binary assignment problem but simply looking for the class which is present the most in each cluster, worked well enough in our case. Keep in mind that the evaluation for overclustering is characterized by a 'many-to-one' mapping and therefore not directly comparable to the results when the amount of clusters equals the amount of ground truth classes. In the limit you have a cluster for every sample in your dataset, always resulting in 100% accuracy.

Hope this helps.

**Comment by wvangansbeke** [comment]
Feel free to ask more questions if something is unclear. I'm closing this for now.

**Comment by chaosfengz** [comment]
@wvangansbeke is the overclustering code in this repository? Seems like one can only do Hungarian match in the eval.py code.

**Comment by wvangansbeke** [comment]
Hi @chaosfengz,

Thank you for your interest.
Indeed, the overclustering part is not present in this codebase. We simply looked for the majority class in every cluster. I think this is fair. A better way would be to solve a binary assignment problem as mentioned before.  

Hope this helps.
