### ISSUE TITLE
Backbone not frozen during SCAN training

### ISSUE THREAD

**Issue by eugenelet** [wvangansbeke/Unsupervised-Classification#33]
Hi there,

Thanks for contributing such a great work to the community. 

It is mentioned in the Supplementary materials in the paper (Clustering Step of ImageNet) that the weights of the backbone are frozen during SCAN training. From the code, this doesn't apply for the training of smaller datasets. Is it because of the longer runtime required for ImageNet that leads to the requirement of weight-freeze during SCAN training? How does the performance compare if the weights are frozen for the small dataset case? 

If the weights are not frozen during SCAN training, doesn't it mean that the extracted embeddings might deviate from the stored memory during pretext training? I assume that such deviation would affect the original kNN results and speculate that the continual update of the neighbor-memory would result in better performance in the SCAN training step.

**Comment by wvangansbeke** [comment]
Hi @eugenelet,

Thank you for your interest. 

The weights are kept frozen during SCAN training, since it is hard to train with a large enough batch size on ImageNet (memory consumption). In general you want large batch sizes for clustering such that all clusters are represented in every batch update. When there are a lot of classes, this becomes more and more difficult. Keeping a memory bank might get rid of this problem as they do in MoCo and Swav. I never tried freezing the backbone for the smaller datasets though. 

Yes indeed, you could try updating the kNN. See also issue #4 (second question).

Hope this helps.

**Comment by eugenelet** [comment]
Thanks for the prompt reply. Your explanation is of great help in understanding the provided code.

The limitation on GPU memory makes sense. 

As mentioned in #4 what does it mean when you mention that through the iterative update of kNN memory, it will be difficult to exploit the self-labeling?

**Comment by wvangansbeke** [comment]
Yes exactly. That's what I assume but I'm certainly not sure though. 
Good luck!

**Comment by eugenelet** [comment]
Thanks for sharing your thoughts. I'll try some experiments to see if that's the case. Appreciate your replies! ;)
