### ISSUE TITLE
About KNN in SCAN

### ISSUE THREAD

**Issue by zhunzhong07** [wvangansbeke/Unsupervised-Classification#4]
Hi, thanks for sharing your great work! I have a concern about the KNN in SCAN training.

In the Eq.2 of your paper, you calculate the loss by maximizing the similarities between each anchor and its KNN. However, in your code, it seems that you only maximize the similarity between each anchor and one of its randomly selected KNN, as the dataloder below.

https://github.com/wvangansbeke/Unsupervised-Classification/blob/69aed1cf484b47d3562cdc318dfd5b27ed8c83bf/data/custom_dataset.py#L71-L72

I am not sure if my understanding is correct.

Thanks.

**Comment by wvangansbeke** [comment]
Hi @zhunzhong07,

Yes you're correct. We sample uniformly from the K nearest neighbors during training. Therefore, it is highly likely that the anchor sees a different neighbor in the next epoch. So, if you train long enough it should have the exact same effect as Eq. 2. After all, it is not practical to include a lot of neighbors for every sample during a forward pass, since this does not scale well with the amount K. 

Hope this helps.

**Comment by zhunzhong07** [comment]
Thanks for you quick reply. I have another question. 

In your code, I find that the indices of neighbors only computed once after the self-supervised learning. Why not re-computed the neighbors after each epoch of SCAN. Will this improve the results?

**Comment by wvangansbeke** [comment]
Yes a good point. I never tried it exactly like that (although something similar). It makes sense actually. However, I'm not sure that the representations are going to be much better at that point. I just think that it will be difficult to exploit the selflabling as we currently do. This step basicaly readjusts the decision boundary between classes and updates the representations based on the prototypes of each class.

**Comment by zhunzhong07** [comment]
OK. Thanks for your reply!
