### ISSUE TITLE
Are we passing the corresponding exact label to Unsupervised learning here?

### ISSUE THREAD

**Issue by Praveenk8051** [wvangansbeke/Unsupervised-Classification#40]
In the code of CIFAR10 class [here](https://github.com/wvangansbeke/Unsupervised-Classification/blob/0d102f2134e322bbb7c148b68895c3ca869d33b8/data/cifar.py#L105), it takes targets and data. These targets are the list of categories in numeric format. The `__getitem__` returns numpy array of corresponding image values. According to definition of **Unsupervised** this shouldn't be the case. Considering the liberty of dataset, CIFAR10(labelled), this kind of implementation works, I think.

**Question**:
How can I pass the targets to my custom dataset ? Can i just pass random numbers, example 3 classes problem(0,1,2)?

But i know how many classes are there. I'm little confused with the implementation any help would be appreciated.

**Comment by wvangansbeke** [comment]
Hi,

In order to evaluate, we require labels. Otherwise how do you think we are able to compute ACC, NMI, ARI when comparing with prior work? 
We simply use the labels to monitor the progress. Please have a look at the paper for more information about the validation criterion to select the best model (without the use of labels). 
We put a lot of effort to make the code easy to understand, transparent and reproducible. Maybe try running the code on cifar10 first, so you get familiar with it. 
Nothing prevents you from making your own dataloader if you want to test it on a new dataset. You won't be able to evaluate if you don't have any labels of course. You can try with random numbers but that's just a weird thing to do. 

Hope this helps.
Cheers.

**Comment by wvangansbeke** [comment]
If you have any further questions, please let me know. Closing this for now.
