### ISSUE TITLE
About number of classes

### ISSUE THREAD

**Issue by isldev** [wvangansbeke/Unsupervised-Classification#45]
is it possible in anyway to get an idea or estimate of the optimum number of classes/clusters from the pretext step without specifying the `num_classes` and to use that number during the second step where the actual clustering takes place? This use case is for a custom dataset where the number of actual cluster is not known beforehand. Any help would be appreciated. Thank you!

**Comment by wvangansbeke** [comment]
Hi @isldev,

Thank you for your interest in our work. 

In practice, I believe it should be possible to make a decent guess. Overclustering so that the clusters are more or less uniform, is the best thing you can do. 

There exist clustering algorithms that do not require you to know the amount of clusters, e.g. Mean Shift. However such algorithms need other parameters like 'clustering bandwidth' for example.

Let's be honest, if you don't know anything about the data, it's hard to learn from it. In all the current unsupervised algorithms, prior knowledge (like uniformity, class dissimilarity, etc.) is in some way exploited.

To answer you question, I think it can be possible to make a decent guess based on the feature space after the first step. However, you will always need some heuristics to do the final clustering.
