### ISSUE TITLE
Question about results

### ISSUE THREAD

**Issue by pp1016** [wvangansbeke/Unsupervised-Classification#51]
In comparison table, does the ACC of **supervised method** also the cluster accuracy (calculate after matching) or just the classification accuracy calculated using actual labels? By the way, did you have the results for CIFAR-100 instead of CIFAR-100-20? Thanks!

**Comment by wvangansbeke** [comment]
Hi @pp1016,

Thanks you for your interest.

Hungarian matching between the predicted clusters and the actual classes is needed in the unsupervised setup to obtain the accuracy metric. For the supervised setup, the matching is not required since the predictions will already align with the ground truth. 

We didn't try CIFAR-100 with 100 classes but always used the 20 superclasses. We do provide results on ImageNet with 100 randomly sampled classes. That might be helpful.

**Comment by pp1016** [comment]
> Hi @pp1016,
> 
> Thank you for your interest.
> 
> Hungarian matching between the predicted clusters and the actual classes is needed in the unsupervised setup to obtain the accuracy metric. For the supervised setup, this matching is not required since the predictions will already align with the ground truth.
> 
> We didn't try CIFAR-100 with 100 classes but always used the 20 superclasses. We do provide results on ImageNet with 100 randomly sampled classes. That might be helpful.

Thanks for help!
