### ISSUE TITLE
Train Scan with Imagenet backbone

### ISSUE THREAD

**Issue by wtt0213** [wvangansbeke/Unsupervised-Classification#65]
Hi, thanks for your excellent work.

I'm try to certificate two things:
1、train scan with imagenet pretrain resnet50, but model is hardly convergence, the acc1 is always 1%(randomly)
2、train scan without fix backbone, but model is hardly convergence, the acc1 is always 1%(randomly)

Do you certificate these experiments and meet similar problems?

**Comment by wvangansbeke** [comment]
Hi @wtt0213,

Thank you for your interest.

No, normally you should get the results from the paper (39.9%). Have a look at the config files for imagenet. Also, are you starting from the MoCo pretrained ResNet50? A possible reason might be that you start from random initialization.  It's also easier to fix the backbone because you would need a very large batch size to train properly on complete imagenet.
