### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by jyrr** [wvangansbeke/Unsupervised-Classification#68]
Hi, thanks for your excellent work and this great repo!

I have trained a pretext (SimCLR) model on my own data, applying KMeans (before MLP head) shows non-random clustering results but not something to write home about. This is due to the low cardinality of the data set (~4000), furthermore there may be overlapping between classes (as my data is as unsupervised as it gets I don't know what features the model would latch on to/how general it is). Before proceding with SCAN I would like to make sure I can get interpretable results, which leads me to a couple of questions.

1. As I understand the model is purposefully started from scratch as it is unsupervised, however would it make sense in this scenario (low cardinality data set) to run my data through a pretrained SimCLR model, or to finetune it on a pretrained SimCLR model?

2. My data comes in various dimensions, I resized the data to 96x96 while maintaining aspect ratio (padded with zeros where necessary). Is this the way to go

3. Unrelated, but have you tried training SimCLR on resolutions greater than 96x96? I'm personally rocking a RTX 3080, 96x96 works fine with batch size 128, however when I tried 224x224 I can't get simclr to work, out of memory for batch size 128 & 64, for 32 I get an error that I haven't figured out yet

I actually have three data sets (~4k, ~21k, ~240k), I would love to be able to, effectively. cluster them all individually. However, another possibility may be to combine all data and train a model from scratch on this. Thank you!

**Comment by jyrr** [comment]
To already answer myself @1, using the pretrained MoCo model followed by KMeans (before MLP head), gives acceptable results, and is applicable, even somewhat for the small dataset I have.

**Comment by wvangansbeke** [comment]
Hi @jyrr,

Thank you for interest.

1. This depends on the type of data you're using and it's size. So to keep it short, try both. Combining the data will probably work better.
2. You can use the same augmentations as we do for ImageNet. Have look at in the `utils/common_config.py` and some of the ImageNet config files.
3. Yes you need a lot of memory in order to obtain sota results with SimCLR. Have look at MoCo or a more recent version with better performance [here](https://github.com/wvangansbeke/Revisiting-Contrastive-SSL). You can train it with a batch of 256 or even 128 (keep in mind to linearly adjust the learning rate).

**Comment by caishaotian-szu** [comment]
Hi, it's a gread honor to read your excellent work.

I've got a problem when I reproduced the result of SCAN-loss based on the cifar-10.  I have trained a clustering model according to the original codes, by running the scan.py based on the best pretext model and default scan-cifar10 parameters. The epoch is set to even 500, but I just got the result of acc = 62%,  unable to reach the best reslut of acc = 81.6% as shown in your paper. 

Could you please help me to answer this question? Thank you!
