### ISSUE TITLE
Question on Backbone

### ISSUE THREAD

**Issue by XingzhiZhou** [wvangansbeke/Unsupervised-Classification#74]
The ResNet18 for the CIFAR is a little bit different from the ResNet18 in pytorch package. The SCAN model removed the maxpool module in ResNet18 for CIFAR.  I have tried ResNet18 from pytorch package, which cannot reach the expected results.

So, what is the intuition to remove the maxpool module in ResNet18 for CIFAR dataset?

Best regards,

**Comment by wvangansbeke** [comment]
Hi @XingzhiZhou,

Thank you for your interest.
Yes this is quite common for images with low resolution (e.g. 32x32 for CIFAR-10). In order to keep more spatial information before the average pool operator, the max pooling layer is removed. Notice that the filter-, stride- and padding size in the  first convolution layer are also different from the conventional implementation. Again, this is to better preserve spatial information.

**Comment by XingzhiZhou** [comment]
Thanks so much for your reply. It helps a lot!
