### ISSUE TITLE
About overclustering and underclustering

### ISSUE THREAD

**Issue by michaelzfm** [wvangansbeke/Unsupervised-Classification#77]
Hi. Thank you for offering the code. I wander if I need to train overclustering or underclustering, which parameter in configuration file should I modify? It is num_classes?

**Comment by wvangansbeke** [comment]
Hi @michaelzfm,

Yes. In order to support overclustering, you'll have to increase `num_classes`. You'll also need to change the evaluation part by implementing a majority voting mechanism in order to get the results from the paper. You can find more info on how to do this in the previous issues #70 #63 #43 #29.

**Comment by wvangansbeke** [comment]
If there are any questions, let us know. Closing this for now.
