### ISSUE TITLE
Using pretrained for my own data

### ISSUE THREAD

**Issue by dabasmoti** [wvangansbeke/Unsupervised-Classification#78]
Hi,
Is it possible to use the imagnet pretrained model on my own data without training?
I can't find any instructions to make an "inference" for clustering.
Thanks

**Comment by wvangansbeke** [comment]
Hi @dabasmoti,

You can find the pretrained model on ImageNet in the readme. Also have a look at `eval.py` for the evaluation or inference. Good luck.

**Comment by dabasmoti** [comment]
@wvangansbeke 
Thank you for the replay.
I tried to make an inference with the `eval.py`
I am using the ImageNet class as DataLoader and I have changed the path to my dataset but got an exception:

` File "/gdrive/MyDrive/project/first_media/videolabelsextractor/Unsupervised-Classification/utils/collate.py", line 32, in collate_custom
    batch_modified = {key: collate_custom([d[key] for d in batch]) for key in batch[0] if key.find('idx') < 0}
  File "/gdrive/MyDrive/project/first_media/videolabelsextractor/Unsupervised-Classification/utils/collate.py", line 32, in <dictcomp>
    batch_modified = {key: collate_custom([d[key] for d in batch]) for key in batch[0] if key.find('idx') < 0}
  File "/gdrive/MyDrive/project/first_media/videolabelsextractor/Unsupervised-Classification/utils/collate.py", line 39, in collate_custom
    raise TypeError(('Type is {}'.format(type(batch[0]))))
TypeError: Type is <class 'PIL.Image.Image'>`


I don't understand why it happened because there is no difference between my data and "ImageNet".
I tried to debug it but with no succes.
Thanks

**Comment by wvangansbeke** [comment]
Hi @dabasmoti,

It looks like your input does not have the correct type or size. Make sure everything is in PIL format for the transformations. Finally you need to feed the network tensors, so use the `ToTensor()` transformation in the end (not Numpy!). Notice that we use a custom `collate` function in order to stack all tensors (see `utils/collate.py`). In order to find the mistake, have a look at the train transformations in `utils/common_config.py` and compare them with yours. You probably forgot to apply `ToTensor()`.

**Comment by wvangansbeke** [comment]
Please let me know if anyting is unclear. Closing this for now.
