### ISSUE TITLE
results on imagenet?

### ISSUE THREAD

**Issue by seyeeet** [wvangansbeke/Unsupervised-Classification#84]
thanks for the great work.
I was wondering if it makes sense to train this model on the whole imagenet-1K?
What do you think is the bottleneck for it?

**Comment by wvangansbeke** [comment]
Hi @seyeeet,

Sure. We did this experiment and achieved 39% (see final table in the paper). You can find a few configs for ImageNet in the `configs/` directory. Feel free to play around with it.  You need a large batch size because ideally every cluster is represented in your batch. So the gpu memory is your bottleneck. From a pratical point of view, it is not that straightforward.

**Comment by seyeeet** [comment]
Thanks a lot for the answer! :)
